create database dbPreguntaDevs;
	create table TBusuarios (usuarioId varchar (20) not null  primary key, nombre1 varchar (20) not null, 
		nombre2 varchar (20) not null, apellido1 varchar (20) not null, apellido2 varchar (20), claveSeguridad varchar (20) not null) 

INSERT INTO tbusuarios(usuarioId, nombre1, nombre2, apellido1, apellido2, claveSeguridad) 
VALUES ("naorellana","nery","alexis","orellana","cuy","aleis01")

UPDATE `tbusuarios` SET `claveSeguridad` = 'alexis01' 
WHERE `tbusuarios`.`usuarioId` = 'naorellana';

INSERT INTO tbusuarios(usuarioId, nombre1, nombre2, apellido1, apellido2, claveSeguridad) 
VALUES ("admin","admin","admin","admin","admin","admin01");

	CREATE TABLE TBPERSONA (
		CORREO VARCHAR (50) NOT NULL UNIQUE, 
		NOMBRE1 VARCHAR (20) NOT NULL, 
		NOMBRE2 VARCHAR (20) NOT NULL, 
		APELLIDO1 VARCHAR (20) NOT NULL, 
		APELLIDO2 VARCHAR(50) NOT NULL, 
		PAIS VARCHAR (20) NOT NULL, 
		FECHANAC DATE  NOT NULL, 
		USUARIO VARCHAR(50) NOT NULL PRIMARY KEY, 
		CONTRASENA VARCHAR (15) NOT NULL);


		CREATE TABLE TEMAS(
			IDTEMA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
			TEMA VARCHAR(20) NOT NULL
		);

		CREATE TABLE ETIQUETAS(
			IDETIQUETA INT NOT NULL AUTO_INCREMENT,
			IDTEMA INT NOT NULL,
			ETIQUETA VARCHAR(20) NOT NULL UNIQUE,
			PRIMARY KEY (IDETIQUETA),
			FOREIGN KEY (IDTEMA) REFERENCES TEMAS(IDTEMA)
		);

		CREATE TABLE NIVEL (
			IDNIVEL INT AUTO_INCREMENT PRIMARY KEY,
			NIVEL VARCHAR(20) NOT NULL
			);

	CREATE TABLE PREGUNTAS (
		IDPREGUNTA INT NOT NULL AUTO_INCREMENT,
		PREGUNTA VARCHAR(140) NOT NULL,
		RESPA VARCHAR(140) NOT NULL,
		RESPB VARCHAR(140) NOT NULL,
		RESPC VARCHAR(140) NOT NULL,
		RESPCORRECTA int(2) NOT NULL,
		USUARIO VARCHAR(20) NOT NULL,
		NIVEL INT NOT NULL,
		ETIQUETA INT NOT NULL,
		PRIMARY KEY (IDPREGUNTA),
		FOREIGN KEY (ETIQUETA) REFERENCES ETIQUETAS(IDETIQUETA),
		FOREIGN KEY (NIVEL) REFERENCES NIVEL(IDNIVEL)
	 );


	INSERT INTO `temas`(`IDTEMA`, `TEMA`) VALUES (0,"PROGRAMACION");
	INSERT INTO `temas`(`IDTEMA`, `TEMA`) VALUES (0,"BASES DE DATOS");

	INSERT INTO `etiquetas`(`IDETIQUETA`, `IDTEMA`, `ETIQUETA`) VALUES (0,1,"JAVA");
	INSERT INTO `etiquetas`(`IDETIQUETA`, `IDTEMA`, `ETIQUETA`) VALUES (0,1,"C++");
	INSERT INTO `etiquetas`(`IDETIQUETA`, `IDTEMA`, `ETIQUETA`) VALUES (0,1,"PHP");

	INSERT INTO `nivel`(`IDNIVEL`, `NIVEL`) VALUES (0,"APRENDÍZ");
	INSERT INTO `nivel`(`IDNIVEL`, `NIVEL`) VALUES (0,"BÁSICO");
	INSERT INTO `nivel`(`IDNIVEL`, `NIVEL`) VALUES (0,"INTERMEDIO");
	INSERT INTO `nivel`(`IDNIVEL`, `NIVEL`) VALUES (0,"AVANZADO");
	INSERT INTO `nivel`(`IDNIVEL`, `NIVEL`) VALUES (0,"EXPERTO");

		INSERT INTO `preguntas`(`IDPREGUNTA`, `PREGUNTA`, `RESPA`, `RESPB`, `RESPC`, `RESPCORRECTA`, `USUARIO`, `NIVEL`, `ETIQUETA`) 
		VALUES (0,"PHP ES UN LENGUAJE DEL LADO DEL SERVIDOR","SI", "NO", "AMBOS", 1,"NORELLANAC",2,3);

		INSERT INTO `preguntas`(`IDPREGUNTA`, `PREGUNTA`, `RESPA`, `RESPB`, `RESPC`, `RESPCORRECTA`, `USUARIO`, `NIVEL`, `ETIQUETA`) 
		VALUES (0,"JAVA ES UN LENGUAJE DE PROGRAMACIÓN ORIENDATO A OBJETOS","SI", "NO", "AMBOS", 1,"NORELLANAC",2,3);
		INSERT INTO `preguntas`(`IDPREGUNTA`, `PREGUNTA`, `RESPA`, `RESPB`, `RESPC`, `RESPCORRECTA`, `USUARIO`, `NIVEL`, `ETIQUETA`) 
		VALUES (0,"GO ES UN LENGUAJE DESAROLLADO POR GOOGLE","SI", "NO", "FALSO", 1,"NORELLANAC",2,3);
		INSERT INTO `preguntas`(`IDPREGUNTA`, `PREGUNTA`, `RESPA`, `RESPB`, `RESPC`, `RESPCORRECTA`, `USUARIO`, `NIVEL`, `ETIQUETA`) 
		VALUES (0,"HTML ES UN LENGUAJE DE PROGRAMACIÓN","SI", "NO", "FALSO", 1,"NORELLANAC",2,3);
		INSERT INTO `preguntas`(`IDPREGUNTA`, `PREGUNTA`, `RESPA`, `RESPB`, `RESPC`, `RESPCORRECTA`, `USUARIO`, `NIVEL`, `ETIQUETA`) 
		VALUES (0,"CSS ES UTILIZADO PARA DAR FORMATO A DOCUMENTOS HTML","SI", "NO", "FALSO", 1,"NORELLANAC",2,3);

		INSERT INTO `PREGUNTAS`(`IDPREGUNTA`, `PREGUNTA`, `RESPA`, `RESPB`, `RESPC`, `RESPCORRECTA`, `USUARIO`, `NIVEL`, `ETIQUETA`) 
		VALUES (0,"JAVA ES UN LENGUAJE DE PROGRAMACIÓN ORIENDATO A OBJETOS","SI", "NO", "AMBOS", 1,"NORELLANAC",2,3);
		INSERT INTO `PREGUNTAS`(`IDPREGUNTA`, `PREGUNTA`, `RESPA`, `RESPB`, `RESPC`, `RESPCORRECTA`, `USUARIO`, `NIVEL`, `ETIQUETA`) 
		VALUES (0,"GO ES UN LENGUAJE DESAROLLADO POR GOOGLE","SI", "NO", "FALSO", 1,"NORELLANAC",2,3);
		INSERT INTO `PREGUNTAS`(`IDPREGUNTA`, `PREGUNTA`, `RESPA`, `RESPB`, `RESPC`, `RESPCORRECTA`, `USUARIO`, `NIVEL`, `ETIQUETA`) 
		VALUES (0,"HTML ES UN LENGUAJE DE PROGRAMACIÓN","SI", "NO", "FALSO", 1,"NORELLANAC",2,3);
		INSERT INTO `PREGUNTAS`(`IDPREGUNTA`, `PREGUNTA`, `RESPA`, `RESPB`, `RESPC`, `RESPCORRECTA`, `USUARIO`, `NIVEL`, `ETIQUETA`) 
		VALUES (0,"CSS ES UTILIZADO PARA DAR FORMATO A DOCUMENTOS HTML","SI", "NO", "FALSO", 1,"NORELLANAC",2,3);

	SELECT preguntas.PREGUNTA, nivel.NIVEL, temas.TEMA FROM `preguntas`, `nivel`, temas, 
	WHERE preguntas.NIVEL=nivel.IDNIVEL and  preguntas.IDPREGUNTA=1;



	/* USAR ESTO PARA LA BASE DE DATOS DE HOSTINGER/*/*/*//*/*/*/
INSERT INTO `TEMAS`(`IDTEMA`, `TEMA`) VALUES (0,"PROGRAMACION");
	INSERT INTO `TEMAS`(`IDTEMA`, `TEMA`) VALUES (0,"BASES DE DATOS");

	INSERT INTO `ETIQUETAS`(`IDETIQUETA`, `IDTEMA`, `ETIQUETA`) VALUES (0,1,"JAVA");
	INSERT INTO `ETIQUETAS`(`IDETIQUETA`, `IDTEMA`, `ETIQUETA`) VALUES (0,1,"C++");
	INSERT INTO `ETIQUETAS`(`IDETIQUETA`, `IDTEMA`, `ETIQUETA`) VALUES (0,1,"PHP");

	INSERT INTO `NIVEL`(`IDNIVEL`, `NIVEL`) VALUES (0,"APRENDÍZ");
	INSERT INTO `NIVEL`(`IDNIVEL`, `NIVEL`) VALUES (0,"BÁSICO");
	INSERT INTO `NIVEL`(`IDNIVEL`, `NIVEL`) VALUES (0,"INTERMEDIO");
	INSERT INTO `NIVEL`(`IDNIVEL`, `NIVEL`) VALUES (0,"AVANZADO");
	INSERT INTO `NIVEL`(`IDNIVEL`, `NIVEL`) VALUES (0,"EXPERTO");

		INSERT INTO `PREGUNTAS`(`IDPREGUNTA`, `PREGUNTA`, `RESPA`, `RESPB`, `RESPC`, `RESPCORRECTA`, `USUARIO`, `NIVEL`, `ETIQUETA`) 
		VALUES (0,"PHP ES UN LENGUAJE DEL LADO DEL SERVIDOR","SI", "NO", "AMBOS", 1,"NORELLANAC",2,3);

	*/


/*---triguers---*/

CREATE PROCEDURE GENERAR_USUARIO (NOM1 VARCHAR(20),APE1 VARCHAR(20),APE2 VARCHAR(20))
UPDATE `tbpersona` SET `USUARIO`=CONCAT (LEFT(NOM1,1),APE1, LEFT(APE2,1)) WHERE `USUARIO`=A1



	CREATE PROCEDURE AGREGAR_USUARIO (CORREO VARCHAR(50),NOM1 VARCHAR(20), NOM2 VARCHAR(20),APE1 VARCHAR(20),APE2 VARCHAR(20),PAIS VARCHAR(20),FECHAN DATE)
	INSERT INTO `tbpersona`(`CORREO`, `NOMBRE1`, `NOMBRE2`, `APELLIDO1`, `APELLIDO2`, `PAIS`, `FECHANAC`, `USUARIO`, `CONTRASENA`) 
	VALUES (CORREO, NOM1,NOM2, APE1, APE2, PAIS, FECHAN, APE1, CONCAT(APE1,"01$"))


DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `NUEVO_USUARIO`(IN `CORREO` VARCHAR(50), IN `NOM1` VARCHAR(20), IN `NOM2` VARCHAR(20), IN `APE1` VARCHAR(20), IN `APE2` VARCHAR(20), IN `PAIS` VARCHAR(20), IN `FECHAN` DATE)
BEGIN
INSERT INTO `tbpersona`(`CORREO`, `NOMBRE1`, `NOMBRE2`, `APELLIDO1`, `APELLIDO2`, `PAIS`, `FECHANAC`, `USUARIO`, `CONTRASENA`) 
	VALUES (CORREO, NOM1,NOM2, APE1, APE2, PAIS, FECHAN, APE1, CONCAT(APE1,"01$"));
UPDATE `tbpersona` SET `USUARIO`=CONCAT (LEFT(NOM1,1),APE1, LEFT(APE2,1)) WHERE `USUARIO`=APE1;
END$$
DELIMITER ;
/*

/*---triguers---*/


/**PROCEDIMIENTOS FUNCIONANDO EN HOSTINGER */

DELIMITER $$
CREATE or replace PROCEDURE `NUEVO_USUARIO`(IN `CORREO` VARCHAR(50), IN `NOM1` VARCHAR(20), IN `NOM2` VARCHAR(20), IN `APE1` VARCHAR(20), IN `APE2` VARCHAR(20), IN `PAIS` VARCHAR(20), IN `FECHAN` DATE)
BEGIN
INSERT INTO `TBPERSONA`(`CORREO`, `NOMBRE1`, `NOMBRE2`, `APELLIDO1`, `APELLIDO2`, `PAIS`, `FECHANAC`, `USUARIO`, `CONTRASENA`) 
	VALUES (CORREO, NOM1,NOM2, APE1, APE2, PAIS, FECHAN, APE1, CONCAT(APE1,"01$"));
UPDATE `TBPERSONA` SET `USUARIO`=LOWER(CONCAT (LEFT(NOM1,1),APE1, LEFT(APE2,1))) WHERE `USUARIO`=APE1;
END$$
DELIMITER ;

CALL NUEVO_USUARIO ("alexis_oc@yahoo.es","Nery","Alexis","Orellana","Cuy","Guatemala","1994/01/07");

/**PROCEDIMIENTOS FUNCIONANDO EN HOSTINGER */