create database dbPreguntaDevs;
	create table TBusuarios (usuarioId varchar (20) not null  primary key, nombre1 varchar (20) not null, 
		nombre2 varchar (20) not null, apellido1 varchar (20) not null, apellido2 varchar (20), claveSeguridad varchar (20) not null) 

INSERT INTO tbusuarios(usuarioId, nombre1, nombre2, apellido1, apellido2, claveSeguridad) 
VALUES ("naorellana","nery","alexis","orellana","cuy","aleis01")

UPDATE `tbusuarios` SET `claveSeguridad` = 'alexis01' 
WHERE `tbusuarios`.`usuarioId` = 'naorellana';

INSERT INTO tbusuarios(usuarioId, nombre1, nombre2, apellido1, apellido2, claveSeguridad) 
VALUES ("admin","admin","admin","admin","admin","admin01");

	CREATE TABLE TBPERSONA (
		CORREO VARCHAR (50) NOT NULL UNIQUE, 
		NOMBRE1 VARCHAR (20) NOT NULL, 
		NOMBRE2 VARCHAR (20) NOT NULL, 
		APELLIDO1 VARCHAR (20) NOT NULL, 
		APELLIDO2 VARCHAR(50) NOT NULL, 
		PAIS VARCHAR (20) NOT NULL, 
		FECHANAC DATE  NOT NULL, 
		USUARIO VARCHAR(50) NOT NULL PRIMARY KEY, 
		CONTRASENA VARCHAR (15) NOT NULL);


		CREATE TABLE TEMAS(
			IDTEMA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
			TEMA VARCHAR(20) NOT NULL
		);

		CREATE TABLE ETIQUETAS(
			IDETIQUETA INT NOT NULL AUTO_INCREMENT,
			IDTEMA INT NOT NULL,
			ETIQUETA VARCHAR(20) NOT NULL UNIQUE,
			PRIMARY KEY (IDETIQUETA),
			FOREIGN KEY (IDTEMA) REFERENCES TEMAS(IDTEMA)
		);

		CREATE TABLE NIVEL (
			IDNIVEL INT AUTO_INCREMENT PRIMARY KEY,
			NIVEL VARCHAR(20) NOT NULL
			);

	CREATE TABLE PREGUNTAS (
		IDPREGUNTA INT NOT NULL AUTO_INCREMENT,
		PREGUNTA VARCHAR(140) NOT NULL,
		RESPA VARCHAR(140) NOT NULL,
		RESPB VARCHAR(140) NOT NULL,
		RESPC VARCHAR(140) NOT NULL,
		RESPCORRECTA int(2) NOT NULL,
		USUARIO VARCHAR(20) NOT NULL,
		NIVEL INT NOT NULL,
		ETIQUETA INT NOT NULL,
		PRIMARY KEY (IDPREGUNTA),
		FOREIGN KEY (ETIQUETA) REFERENCES ETIQUETAS(IDETIQUETA),
		FOREIGN KEY (NIVEL) REFERENCES NIVEL(IDNIVEL)
	 );


	INSERT INTO `temas`(`IDTEMA`, `TEMA`) VALUES (0,"PROGRAMACION");
	INSERT INTO `temas`(`IDTEMA`, `TEMA`) VALUES (0,"BASES DE DATOS");

	INSERT INTO `etiquetas`(`IDETIQUETA`, `IDTEMA`, `ETIQUETA`) VALUES (0,1,"JAVA");
	INSERT INTO `etiquetas`(`IDETIQUETA`, `IDTEMA`, `ETIQUETA`) VALUES (0,1,"C++");
	INSERT INTO `etiquetas`(`IDETIQUETA`, `IDTEMA`, `ETIQUETA`) VALUES (0,1,"PHP");

	INSERT INTO `nivel`(`IDNIVEL`, `NIVEL`) VALUES (0,"APRENDÍZ");
	INSERT INTO `nivel`(`IDNIVEL`, `NIVEL`) VALUES (0,"BÁSICO");
	INSERT INTO `nivel`(`IDNIVEL`, `NIVEL`) VALUES (0,"INTERMEDIO");
	INSERT INTO `nivel`(`IDNIVEL`, `NIVEL`) VALUES (0,"AVANZADO");
	INSERT INTO `nivel`(`IDNIVEL`, `NIVEL`) VALUES (0,"EXPERTO");

		INSERT INTO `preguntas`(`IDPREGUNTA`, `PREGUNTA`, `RESPA`, `RESPB`, `RESPC`, `RESPCORRECTA`, `USUARIO`, `NIVEL`, `ETIQUETA`) 
		VALUES (0,"PHP ES UN LENGUAJE DEL LADO DEL SERVIDOR","SI", "NO", "AMBOS", 1,"NORELLANAC",2,3);

	SELECT preguntas.PREGUNTA, nivel.NIVEL, temas.TEMA FROM `preguntas`, `nivel`, temas, 
	WHERE preguntas.NIVEL=nivel.IDNIVEL and  preguntas.IDPREGUNTA=1;



	/* USAR ESTO PARA LA BASE DE DATOS DE HOSTINGER/*/*/*//*/*/*/
INSERT INTO `TEMAS`(`IDTEMA`, `TEMA`) VALUES (0,"PROGRAMACION");
	INSERT INTO `TEMAS`(`IDTEMA`, `TEMA`) VALUES (0,"BASES DE DATOS");

	INSERT INTO `ETIQUETAS`(`IDETIQUETA`, `IDTEMA`, `ETIQUETA`) VALUES (0,1,"JAVA");
	INSERT INTO `ETIQUETAS`(`IDETIQUETA`, `IDTEMA`, `ETIQUETA`) VALUES (0,1,"C++");
	INSERT INTO `ETIQUETAS`(`IDETIQUETA`, `IDTEMA`, `ETIQUETA`) VALUES (0,1,"PHP");

	INSERT INTO `NIVEL`(`IDNIVEL`, `NIVEL`) VALUES (0,"APRENDÍZ");
	INSERT INTO `NIVEL`(`IDNIVEL`, `NIVEL`) VALUES (0,"BÁSICO");
	INSERT INTO `NIVEL`(`IDNIVEL`, `NIVEL`) VALUES (0,"INTERMEDIO");
	INSERT INTO `NIVEL`(`IDNIVEL`, `NIVEL`) VALUES (0,"AVANZADO");
	INSERT INTO `NIVEL`(`IDNIVEL`, `NIVEL`) VALUES (0,"EXPERTO");

		INSERT INTO `PREGUNTAS`(`IDPREGUNTA`, `PREGUNTA`, `RESPA`, `RESPB`, `RESPC`, `RESPCORRECTA`, `USUARIO`, `NIVEL`, `ETIQUETA`) 
		VALUES (0,"PHP ES UN LENGUAJE DEL LADO DEL SERVIDOR","SI", "NO", "AMBOS", 1,"NORELLANAC",2,3);

	*/

		